server:
  servlet:
    context-path: /demo
  port: 8888
spring:
  datasource:
    druid:
#      url: jdbc:mysql://192.168.1.200:5306/dev?characterEncoding=utf8&allowMultiQueries=true
      url: jdbc:mysql://192.168.1.200:8306/dev?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&allowMultiQueries=true
      username: nan
      password: dream7788
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1   # 连接池初始化大小
      min-idle: 1       # 连接池最小数量
      max-active: 20    # 连接池最大数量
      max-wait: 60000   # 获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x'   # 用来检测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true         # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false         # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false         # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false  # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      # max-open-prepared-statements: 20  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      async-init: true
      filters: stat,slf4j
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.json,/druid/*"  # 排除一些不必要的url
        url-pattern: /*
        session-stat-enable: false
#        session-stat-max-count: 1000
#        principal-session-name: loginUser # Session中当前用户标识
#        principal-cookie-name: loginUser  # Cookie中当前用户标识
#        profile-enable: true    # 监控单个url调用的sql列表
      stat-view-servlet:
        enabled: true
        login-username: nan         # 登录用户名
        login-password: dream7788   # 登录密码
        url-pattern: /druid/*
        reset-enable: false   #禁止所有计数器清零
        allow: 192.168.1.1/24
      aop-patterns: com.guonanjun.demo.manager
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: true
        slf4j:
          enabled: true
          connection-log-enabled: false
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
          statement-execute-query-after-log-enabled: false
  aop:
    proxy-target-class: true
mybatis:
  mapper-locations: classpath:mapper/demo/*.xml
  type-aliases-package: com.guonanjun.demo.model
  type-handlers-package: com.guonanjun.demo.mapper
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  config: classpath:log4j2.yml
